name = Notes Book
description = Notes Book layout.
preview = preview.png
template = notes_book-layout

; Regions
regions[notes_book_title] = Title
regions[notes_book_body] = Body
regions[notes_book_updated] = Date updated
regions[notes_book_toc] = Book table of contents
regions[notes_book_nav] = Book navigation

; Stylesheets
stylesheets[all][] = css/layouts/notes_book/notes_book.layout.css

; Scripts
